language: python
python:
    - "2.7"

# command to install dependencies
install:
    - pip install -r requirements.txt --use-mirrors
    - echo $PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:/home/travis/build/GustavePate/distarkcli/distarkcli/protos/
    - echo $PYTHONPATH
# command to run tests
script: 
    - echo $PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:/home/travis/build/GustavePate/distarkcli/distarkcli/protos/
    - echo $PYTHONPATH
    - make test.travis

# branch whitelist
branches:
   only:
       - master
